name: PublishDocumentation

on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        config: .jazzy.yaml
